title: PatFolio
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs
kramdown:
  math_engine: mathjax
  input: GFM


logo: "/assets/images/just-the-docs.png"

include: 
 - IA
 - IA/smallproject
 - IA/smallproject/wwwroot
 - IA/smallproject/wwwroot/_framework
