version: '3'

services:
  jekyll:
    image: ruby:3.1
    working_dir: /srv/jekyll
    command: bash -c "gem install bundler && bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling --watch"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll


